### ISSUE TITLE
Test bob.extension.test_utils.test_documentation_generation failing on nighlies

### ISSUE THREAD

**Issue by tiagofrepereira2012** [bioidiap/bob.extension#15]
The test bob.extension.test_utils.test_documentation_generation failing on nighlies

```
======================================================================
FAIL: bob.extension.test_utils.test_documentation_generation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/remote/gitlab-ci-runner/tmp/builds/3ae32669/0/biometric/bob.nightlies/layers/0/bob.extension/bob/extension/test_utils.py", line 194, in test_documentation_generation
    nose.tools.eq_(result, expected)
AssertionError: {'http://matplotlib.sourceforge.net': None, 'https://www.idiap.ch/software/bob/docs/latest/idiap/gridtk/master': None, 'http://docs.python.org/2.7': None} != {'http://matplotlib.sourceforge.net': None, 'https://www.idiap.ch/software/bob/docs/latest/idiap/gridtk/master': None, 'https://www.idiap.ch/software/bob/docs/latest/bioidiap/bob.extension/master': None, 'http://docs.python.org/2.7': None}======================================================================
FAIL: bob.extension.test_utils.test_documentation_generation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/remote/gitlab-ci-runner/tmp/builds/3ae32669/0/biometric/bob.nightlies/layers/0/bob.extension/bob/extension/test_utils.py", line 194, in test_documentation_generation
    nose.tools.eq_(result, expected)
AssertionError: {'http://matplotlib.sourceforge.net': None, 'https://www.idiap.ch/software/bob/docs/latest/idiap/gridtk/master': None, 'http://docs.python.org/2.7': None} != {'http://matplotlib.sourceforge.net': None, 'https://www.idiap.ch/software/bob/docs/latest/idiap/gridtk/master': None, 'https://www.idiap.ch/software/bob/docs/latest/bioidiap/bob.extension/master': None, 'http://docs.python.org/2.7': None}
```

**Comment by tiagofrepereira2012** [comment]
For some reason the link https://www.idiap.ch/software/bob/docs/latest/bioidiap/bob.extension/master was unreachable.
I will start the restart the builds

**Comment by tiagofrepereira2012** [comment]
All **green** with the nightlies
