### ISSUE TITLE
Tests fail when a secure connection fails

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.extension#17]
So this test is failing:
```

======================================================================
FAIL: bob.extension.test_utils.test_documentation_generation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/bob/extension/test_utils.py", line 194, in test_documentation_generation
    nose.tools.eq_(result, expected)
AssertionError: {'http://matplotlib.sourceforge.net': None, 'https://www.idiap.ch/software/bob/docs/latest/idiap/gridtk/master': None, 'http://docs.python.org/2.7': None} != {'http://matplotlib.sourceforge.net': None, 'https://www.idiap.ch/software/bob/docs/latest/idiap/gridtk/master': None, 'https://www.idiap.ch/software/bob/docs/latest/bioidiap/bob.extension/master': None, 'http://docs.python.org/2.7': None}

----------------------------------------------------------------------
```
This is happening because `https://www.idiap.ch/software/bob/docs/latest/bioidiap/bob.extension/master` cannot be accessed now and fails with this error in firefox: 
```
Secure Connection Failed

An error occurred during a connection to www.idiap.ch. Peer's certificate has an invalid signature. Error code: SEC_ERROR_BAD_SIGNATURE

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…
```

The question is why I don't see this error in the log: https://circleci.com/gh/conda-forge/bob.extension-feedstock/31 ?
Is it because of this line: https://github.com/bioidiap/bob.extension/blob/master/bob/extension/utils.py#L517

**Comment by siebenkopf** [comment]
I don't think that this line is actually the problem. I hope that ``SEC_ERROR_BAD_SIGNATURE`` is not giving error code ``404``. In fact, I don't even know, which kind of error is raised. 

Maybe you don't see the error message, because you don't see any message. At least for the other (successful) packages, you should be able to see:
https://github.com/bioidiap/bob.extension/blob/master/bob/extension/utils.py#L514
which doesn't show up in your build either. You should check your ``nosetest`` parameters...

**Comment by tiagofrepereira2012** [comment]
Just connecting this issue with this one (Issue #15).
Some builds on nighties are failing

**Comment by tiagofrepereira2012** [comment]
Just for documentation purposes, the issue raises `URLError` not `HTTPError`
